language: node_js
node_js:
  - "node"
script:
  - yarn run docs:build
deploy:
  provider: pages
  local_dir: _book
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  on:
    branch: master
cache:
  yarn: true