language: node_js
node_js:
  - "node"
script:
  - yarn run docs:build
deploy:
  provider: pages
  local_dir: _book
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  on:
    branch: master
cache:
  yarn: true
notifications:
  slack:
    secure: tK2DqSvXVDL+7x9kxP/1fqY+qvnZ7afoIP8i4QCRF6Brsw/NAYH6PbTweNxyeWOdmFKyItfNnAGS/44ADrLuZeprPAQpPf7Ekc6c4fc6kGNNGoEpW70Rn4RJriCHBecboRlMJ+uR6yf4iEkhTSrhKN9s/W8r1iNCAU1t6p2B6wZ1EpZTC5VBmsarq/aIpft0dzCG15noZMB21zFUc04WtnA271cgEyHHFnhawzNHGL19HlRe3q54QKs+9A+TaPZbMc84sbeAnnmcFmKRjFNzNN+0jH7mdsbNgYEkBGTciV5VzU4ib4s62kF4EFMyE9CFnmucopMKi/o0PEt9xfwLqd/M3VXpkKVYXyF9ajH7XsiI7X/1dlSii2c+GglnVp/o1s5aviy0D8XAwZhQuKjBkh6UVrNRnh7kkaCOs9Z1jDH7InqcNzkqAPWgPq6NKgvXYAWP5ujrPQehdY4RXm23WiCPgs9ANdbnMyEaBfgUmhP4yTQ12OSEkSdeO/cvJTyN2YiglcAfEUYZlp2nIZFw4ZOU/Tk/aFH4q32Jt2lbz9OWZ8Yyae4/jju2qDoc3t4QXHkd2vSFenT0Z6UtzzN0alqgGv45cyIkjJWGw6UYEggneV3URB8liedlJFo8NU1p1P4I0RHKk9nCTQXzBw6rjeHBP3imUrAyn3y2GAhliT4=
